### ISSUE TITLE
Cannot find module './server'

### ISSUE THREAD

**Issue by neverfox** [maxtaco/coffee-script#105]
The following app.js code works with 1.6.3-g but gives `Cannot find module './server'` with 1.6.3-j:

``` javascript
require('iced-coffee-script')
server = require("./server");
```

server.iced is in the same directory as app.js. I simply run `node app.js`.
